###
### 생성한 userId에 맞춰서 아래와 같이 실행후 account table확인해보면
### PREPAID type의 account의 amounts가 50000이 된것을 확인할 수 있음.
### CREDIT PREPAID ACCOUNT
POST http://localhost:8080/api/wallet/PREPAID/credit/test1?amount=50000
Content-Type: application/json