spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/jpa_lecture
    username : root
    password: admin
  flyway:
    enabled: false

logging:
  config: classpath:logback-local.xml